import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Featured from '@/components/Featured'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Pizza App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="Best Pizza Restaurant" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/2094/2094661.png" />
      </Head>
      <Featured/>

    </div>

  )
}
