import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Featured from '@/components/Featured'
import PizzaList from '@/components/PizzaList'
import BlogPage from '@/components/BlogPage'
import Contact from '@/components/Contact'
import Subscribe from '@/components/Subscribe'
import TopButton from '@/components/TopButton'
import {useState, useEffect} from 'react'


 
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [title, setTitle] = useState("Pizza App")

useEffect(()=> {
  const handleVisibilityChange = () => {
    if(document.hidden) {
      setTitle("Dont Forget!")
    }else {
      setTitle("Pizza App")
    }
  };
  document.addEventListener("visibilitychange", handleVisibilityChange);

  return () => {
    document.removeEventListener("visibilitychange", handleVisibilityChange);

  }
})
  return (
    <div className={styles.container}>
      
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="Best Pizza Restaurant" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/2094/2094661.png" />
      </Head>
      <Featured/>
      <PizzaList/>
      <BlogPage/>
      <Contact/>
      <Subscribe/>
      <TopButton/>
    </div>

  )
}
